package com.example.n_u.officebotapp.utils;

import android.content.Context;

/**
 * ResourceUtils
 *
 * @author <a href="http://www.trinea.cn" target="_blank">Trinea</a> 2012-5-26
 */
public class ResourceUtils {

    private ResourceUtils() {
        throw new AssertionError();
    }

    /**
     * get an asset using ACCESS_STREAMING mode. This provides access to files that have been bundled with an
     * application as assets -- that is, files placed in to the "assets" directory.
     *
     * @param context
     * @param fileName The name of the asset to open. This name can be hierarchical.
     * @return
     */
    public static String geFileFromAssets(android.content.Context context, String fileName) {
        if (context == null || android.text.TextUtils.isEmpty(fileName)) {
            return null;
        }

        StringBuilder s = new StringBuilder("");
        try {
            java.io.InputStreamReader in = new java.io.InputStreamReader(context.getResources().getAssets().open(fileName));
            java.io.BufferedReader br = new java.io.BufferedReader(in);
            String line;
            while ((line = br.readLine()) != null) {
                s.append(line);
            }
            return s.toString();
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * get content from a raw resource. This can only be used with resources whose value is the name of an asset files
     * -- that is, it can be used to open drawable, sound, and raw resources; it will fail on string and color
     * resources.
     *
     * @param context
     * @param resId   The resource identifier to open, as generated by the appt tool.
     * @return
     */
    public static String geFileFromRaw(android.content.Context context, int resId) {
        if (context == null) {
            return null;
        }

        StringBuilder s = new StringBuilder();
        try {
            java.io.InputStreamReader in = new java.io.InputStreamReader(context.getResources().openRawResource(resId));
            java.io.BufferedReader br = new java.io.BufferedReader(in);
            String line;
            while ((line = br.readLine()) != null) {
                s.append(line);
            }
            return s.toString();
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * same to {@link ResourceUtils#geFileFromAssets(Context, String)}, but return type is List<String>
     *
     * @param context
     * @param fileName
     * @return
     */
    public static java.util.List<String> geFileToListFromAssets(android.content.Context context, String fileName) {
        if (context == null || android.text.TextUtils.isEmpty(fileName)) {
            return null;
        }

        java.util.List<String> fileContent = new java.util.ArrayList<String>();
        try {
            java.io.InputStreamReader in = new java.io.InputStreamReader(context.getResources().getAssets().open(fileName));
            java.io.BufferedReader br = new java.io.BufferedReader(in);
            String line;
            while ((line = br.readLine()) != null) {
                fileContent.add(line);
            }
            br.close();
            return fileContent;
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * same to {@link ResourceUtils#geFileFromRaw(Context, int)}, but return type is List<String>
     *
     * @param context
     * @param resId
     * @return
     */
    public static java.util.List<String> geFileToListFromRaw(android.content.Context context, int resId) {
        if (context == null) {
            return null;
        }

        java.util.List<String> fileContent = new java.util.ArrayList<String>();
        java.io.BufferedReader reader = null;
        try {
            java.io.InputStreamReader in = new java.io.InputStreamReader(context.getResources().openRawResource(resId));
            reader = new java.io.BufferedReader(in);
            String line = null;
            while ((line = reader.readLine()) != null) {
                fileContent.add(line);
            }
            reader.close();
            return fileContent;
        } catch (java.io.IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}